apps/sending_emails/urls.py
from django.urls import path

from .views import CreateGroupForEmailView, EmailCreateView, EmailDeleteView, \
    HomePage, SendMessageEmailView

app_name = 'email'

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('create_email/', EmailCreateView.as_view(), name='create_email'),
    path('create_group/', CreateGroupForEmailView.as_view(),
         name='create_group'),
    path('email/<int:pk>/', SendMessageEmailView.as_view(),
         name='detail_email'),
    path('email/<int:pk>/delete/', EmailDeleteView.as_view(),
         name='delete_email'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('apps.users.urls')),
    path('', include('apps.sending_emails.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <title>{{title}}</title>
</head>
<body>
    <!-- start navbar -->
    {% include 'inc/_navbar.html' %}
      <!-- end navbar -->
<div class="container mt-5 mb-10">
    {% block content %}
    {% endblock %}




<!-- footer -->
{% include 'inc/_footer.html' %}

      
</div>

<!-- 
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script> -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %} Главная {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<p class="h1">ГЛАВНАЯ</p>
{% include 'inc/_messages.html' %}

{% if emails %}
<div class="card">
    <p class="h1 text-center">Электронные почты:</p>
    {% for email in emails %}
    <div class="card-body">
        <h5 class="card-title">{{email.email}}</h5>
        <p class="card-text">Владелец почты: {{email.owner}}</p>
        <p class="card-text"><small class="text-muted">{{email.created}}</small></p>
        {% if email.group %}
        <p class="card-text"><small class="text-muted">{{email.group}}</small></p>
        {% endif %}
        <a href="{{ email.get_absolute_url }}" class="mr"><button class="btn btn-success">Отправить письмо
        </button></a>
        <form action="{% url 'email:delete_email' pk=email.id %}" method="post" style="display: inline;">
          {% csrf_token %}
          <input type="hidden" name="email_id" value="{{ email.id }}"/>
               <button type="submit" class="btn btn-danger btn-small">
                   <span class="glyphicon glyphicon-trash">Удалить</span>
                </button>
        </form>
<!--        <a href="{% url 'email:delete_email' pk=email.id %}" class="mr"><button class="btn btn-danger">Удалить-->
<!--        </button></a>-->

    </div>
<!--    <hr>-->

    {% endfor %}
</div>
{% else %}
<p class="h1">Добро пожаловать на сайт</p>
{% endif %}
<!--TODO отображение email-->
{% endblock %}