apps/sending_emails/urls.py
from django.urls import path

from .views import CreateGroupForEmailView, EmailCreateView, EmailDeleteView, \
    HomePage, SendMessageEmailView

app_name = 'email'

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('create_email/', EmailCreateView.as_view(), name='create_email'),
    path('create_group/', CreateGroupForEmailView.as_view(),
         name='create_group'),
    path('email/<int:pk>/', SendMessageEmailView.as_view(),
         name='detail_email'),
    path('email/<int:pk>/delete/', EmailDeleteView.as_view(),
         name='delete_email'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('apps.users.urls')),
    path('', include('apps.sending_emails.urls')),
]

templates/inc/_footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">

    <a href="/"
       class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"></use>
        </svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#"
                                class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a>
        </li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a>
        </li>
        <li class="nav-item"><a href="#"
                                class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#"
                                class="nav-link px-2 text-muted">About</a></li>
    </ul>
</footer>

templates/inc/_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
    {% endfor %}
</ul>
{% endif %}

templates/inc/_navbar.html
<div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
        <h5 class="text-white h4">Collapsed content</h5>
        <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">


    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link"
                           href="{% url 'email:index' %}">Главная</a>
                </li>
<!--                <li class="nav-item dropdown">-->
<!--                    <a class="nav-link dropdown-toggle" href="#"-->
<!--                       id="navbarDropdownMenuLink" role="button"-->
<!--                       data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                        Работа с почтой-->
<!--                    </a>-->
<!--                    <ul class="dropdown-menu"-->
<!--                        aria-labelledby="navbarDropdownMenuLink">-->
<!--                        <li><a class="dropdown-item"-->
<!--                               href="{% url 'email:create_email' %}">Добавить-->
<!--                            почту</a></li>-->
<!--                        <li><a class="dropdown-item"-->
<!--                               href="{% url 'email:create_group' %}">Добавить-->
<!--                            группу почт</a></li>-->
<!--                    </ul>-->
<!--                </li>-->
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Работа с почтой
                    </a>
                    <ul class="dropdown-menu"
                        aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item"
                               href="{% url 'email:create_email' %}">Добавить
                            почту</a></li>
                        <li><a class="dropdown-item"
                               href="{% url 'email:create_group' %}">Добавить
                            группу почт</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Мой профиль
                    </a>
                    <ul class="dropdown-menu"
                        aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item"
                               href="{% url 'password_change' %}">Изменить
                            пароль</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                <!-- убрать перед деплоем!!!!!! -->
                <li class="nav-item">
                    <a class="nav-link" href="#">{{request.user.username}}</a>
                </li>
                <!--!!!!!! убрать перед деплоем -->
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
                </li>

                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'register' %}">Регистрация</a>
                </li>

                {% endif %}

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search"
                       placeholder="Поиск" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Поиск
                </button>
            </form>
        </div>

    </div>
</nav>

templates/inc/_pagination.html
{% if page_obj.has_other_pages %}
<nav>
  <ul class="pagination mt-3">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}